name: Build Godot APK

on:
  push:
    branches:
      - build-apk
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create export_presets.cfg
        run: |
          cat <<EOT > project/export_presets.cfg
          [preset.0]
          name="Android"
          platform="Android"
          export_path="bin/dungeons-and-drag.apk"
          [preset.0.options]
          custom_template/debug="res://android_debug.apk"
          custom_template/release="res://android_release.apk"
          keystore/release="default"
          EOT

      - name: Build APK
        run: |
          mkdir -p bin
          godot --headless --export-release Android bin/dungeons-and-drag.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dungeons-and-drag.apk
          path: bin/dungeons-and-drag.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/dungeons-and-drag.apk
          tag_name: v1.0.${{ github.run_number }}
          release_name: "Release v1.0.${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
